import type { Metadata } from "next";
import "./globals.css";

import Layout from "../components/Layout"; // Import the Layout component

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <Layout>{children}</Layout> {/* Wrap children with Layout */}
      </body>
    </html>
  );
}
