import type { Metadata } from "next";
import "./globals.css";
import Titlebar from "../components/Titlebar";
import Sidebar from "../components/Siderbar";
import Explorer from "../components/Explorer";
import Bottombar from "../components/Bottombar";
import Tabsbar from "../components/Tabsbar";

export const metadata: any = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <Titlebar />
        <div className="flex h-screen">
          <Sidebar />
          <Explorer />
          <div className="flex-1 flex flex-col">
            <Tabsbar />
            <main
              id="main-editor"
              className="flex-1 overflow-y-auto p-4 bg-gray-100"
            >
              {children}
            </main>
          </div>
        </div>
        <Bottombar />
      </body>
    </html>
  );
}
